AppBundle:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

google_login:
    path: /login/check-google