hayden_pierce_personalizer_home_page:
    path:     /
    defaults: { _controller: HaydenPiercePersonalizerBundle:Default:index }

hayden_pierce_personalizer_browse_page:
    path:     /browse
    defaults: { _controller: HaydenPiercePersonalizerBundle:Browse:index }

hayden_pierce_personalizer_sandbox:
    path:     /sandbox
    defaults: { _controller: HaydenPiercePersonalizerBundle:Sandbox:index }

hayden_pierce_personalizer_OAuthCallback:
    path:     /OAuthCallback
    defaults: { _controller: HaydenPiercePersonalizerBundle:OAuthCallback:index }