hayden_pierce_personalizer_home_page:
    path:     /
    defaults: { _controller: HaydenPiercePersonalizerBundle:Default:index }

hayden_pierce_personalizer_browse_page:
    path:     /browse
    defaults: { _controller: HaydenPiercePersonalizerBundle:Browse:index }

hayden_pierce_personalizer_OAuthCallback:
    path:     /OAuthCallback
    defaults: { _controller: HaydenPiercePersonalizerBundle:OAuthCallback:index }

hayden_pierce_personalizer_Debug:
    path:     /debug
    defaults: { _controller: HaydenPiercePersonalizerBundle:Debug:index }

hayden_pierce_personalizer_login:
    path:     /login
    defaults: { _controller: HaydenPiercePersonalizerBundle:Login:index }

hayden_pierce_personalizer_logout:
    path:     /logout
    defaults: { _controller: HaydenPiercePersonalizerBundle:Logout:index }